version: "3"
services:
  database:
    restart: always
    image: postgis/postgis:13-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"

  cache:
    restart: always
    image: redis:6

  directus:
    restart: always
    image: directus/directus:10.8.2
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    depends_on:
      - cache
      - database
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      CACHE_ENABLED: "false"
      CACHE_STORE: "redis"
      REDIS: "redis://cache:6379"

      CORS_ENABLED: "false"
      CORS_ORIGIN: "http://localhost:3000,http://localhost"
      CORS_METHODS: 'GET,PUT,POST,PATCH,DELETE,HEAD'
      CORS_ALLOWED_HEADERS: 'Content-Type,Authorization'
      CORS_EXPOSED_HEADERS: 'Content-Range'

      ADMIN_EMAIL: "maisvagases@gmail.com"
      ADMIN_PASSWORD: "ronaldo13"

  # Make sure to set this in production
  # (see https://docs.directus.io/self-hosted/config-options#general)
      PUBLIC_URL: "https://cms.maisvagases.com.br"
